# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pre-build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i -g yarn
    - run: yarn install

  build-common:
    needs: pre-build
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - run: yarn --cwd packages/common run build
    - run: ls
    - run: npm test

  build-server:
    needs: [pre-build, build-common]
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - run: yarn --cwd packages/server run build
    - run: ls
